#!/usr/bin/env bash
#install a web server nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/
sudo chmod -R 755 /var/www/
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
