#!/usr/bin/env bash
#redirect me
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    add_header X-Served-By 03-web-02;
    
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _; 

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
sudo service nginx restart
