#!/usr/bin/env bash
#installed nginx
sudo apt-get update
sudo apt-get install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
