#!/usr/bin/env bash
#process and pid file

stopinf() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

for (( ; ; ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && stopinf' SIGTERM
	trap 'stopinf' SIGQUIT
done
