#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

IFS=':'
while read -r password gid info home uid shell home username;
do
	echo "The user $user is part of the $gid gang, lives in $homedir and rides $loginshell. $uid's place is protected by the passcode $pass, more info about the user here: $username_f"
done < "/etc/passwd"
