#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and extra.

a=1
while (( a<=10 ));
do
	if (( a == 4 ));
	then
		echo "bad luck"
	elif (( a == 8 ));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( a++ ))
done
