#!/usr/bin/env bash
#commands used to fix the issue

echo '<VirtualHost *:80>' > /etc/apache2/sites-enabled/000-default.conf
echo '    ServerName localhost' >> /etc/apache2/sites-enabled/000-default.conf
echo '    DocumentRoot /var/www/html' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '    <Directory /var/www/html/>' >> /etc/apache2/sites-enabled/000-default.conf
echo '        Options Indexes FollowSymLinks' >> /etc/apache2/sites-enabled/000-default.conf
echo '        AllowOverride All' >> /etc/apache2/sites-enabled/000-default.conf
echo '        Require all granted' >> /etc/apache2/sites-enabled/000-default.conf
echo '    </Directory>' >> /etc/apache2/sites-enabled/000-default.conf
echo '' >> /etc/apache2/sites-enabled/000-default.conf
echo '    ErrorLog ${APACHE_LOG_DIR}/error.log' >> /etc/apache2/sites-enabled/000-default.conf
echo '    CustomLog ${APACHE_LOG_DIR}/access.log combined' >> /etc/apache2/sites-enabled/000-default.conf
echo '</VirtualHost>' >> /etc/apache2/sites-enabled/000-default.conf
service apache2 restart

