#!/usr/bin/env bash
#commands used to fix the issue
docker exec -it 47ca3994a491 /bin/bash
nano /etc/apache2/sites-enabled/000-default.conf
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 restart
