#!/usr/bin/env bash
#commands used to fix the issue

docker run -p 8080:80 -d -it holbertonschool/265-0
docker exec -it $(docker ps -q) /bin/bash
echo "Hello Holberton" > /var/www/html/index.html
service apache2 restart

